version: '3'
services:
  app:
    container_name: qrpuzzle
    restart: always
    build: .
    ports:
      - '1370:1370'
    volumes:
      - archive:/app/dist/public/archive
      - pdf:/app/dist/public/pdf
volumes: 
  archive:
  pdf:
#networks:
 # default:
  #  external:
   #   name: buroplatform_default